name: on master

on:
  push:
    branches:
      - master

jobs:
  on_master:
    runs-on: ubuntu-latest
    name: Update Notion property
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name:  'Automated Version Bump'
        id: version_bump_and_create_tag
        uses:  rimonhanna/gh-action-bump-version@master

      - name: Upload release notes
        if: steps.version_bump_and_create_tag.outputs.TAG
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version_bump_and_create_tag.outputs.TAG }}
          release_name: ${{ steps.version_bump_and_create_tag.outputs.TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
